### PR TITLE
add sphinx_redirect_layout_page config value

### PR DESCRIPTION
**Pull request by marxin**
The config value allows extending a custom html template, not layout.html.

### CODE REVIEW

**Comment by marxin** [comment]
May I please ping this?

**Comment by jakobandersen** [comment]
Thanks!

**Comment by marxin** [comment]
I thank you. Can you please bump the `pypi` package and link `pypi` in the GitHub project description?

**Comment by marxin** [comment]
Unfortunately, we won't use Sphinx for GCC documentation and so I won't need this extension to be published.
@jakobandersen Sorry for the extra work you did, I really appreciate that.

**Pull request merged**
